### ISSUE TITLE
SSL Certificate Errors

### ISSUE THREAD

**Issue by Throckmorton69** [fiquett/Viper_SmartStart_Control#1]
<br />
<b>Fatal error</b>:  Uncaught exception 'Exception' with message 'Error during GET of 'https://colt.calamp-ts.com/auth/login/**************': SSL certificate problem, verify that the CA cert is OK. Details:
error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed' in D:\WebSites\Test\viper_control.php:66
Stack trace:
#0 D:\WebSites\Test\viper_control.php(152): curlGet('https://colt.ca...', '', true)
#1 D:\WebSites\Test\viper_control.php(45): getSessionID('****_@**_**.**_', '_*******')
#2 {main}

  thrown in <b>D:\WebSites\Test\viper_control.php</b> on line <b>66</b><br />

**Comment by jaxonklein** [comment]
Hi there,
Is the unofficial "API" still working?
Thanks!
